### PR TITLE
Fix lints

### PR DESCRIPTION
**Pull request by SirWindfield**

### CODE REVIEW

**Comment by jplatte** [comment]
I don't see how moving the `#[allow(missing_docs)]` improves anything. I like the before version more. I don't think anybody would ever have a reason to remove the main type docs. With our MSRV now at 1.41, why are we `#[allow]`ing `clippy::manual_non_exhaustive`?

**Comment by SirWindfield** [comment]
Totally forgot about the Msrv.

And ye you're right. I'll clean up tmrw

**Comment by SirWindfield** [comment]
@jplatte Should we add a type declaration, something like `FormatFn`? It would make most sense to make it public so people can use it as well at this point.

**Comment by jplatte** [comment]
Yeah, if we create a type definition for that (which seems like a good idea) it has to be public, if not by Rust's visibility rules then for people to be able to see its definition in the docs.

**Comment by jplatte** [comment]
PR is a bit outdated by now, squashing and rebasing...

**Pull request merged**
